import { Hotel } from "../types/interfaces";

export const hotelsData: Hotel[] = [
  { id: "1", name: "The Bostonian Boston", location: "Boston", pricePerNight: 150, rating: 4.5 },
  { id: "2", name: "The Liberty Hotel", location: "Boston", pricePerNight: 180, rating: 4.7 },
  { id: "3", name: "Hotel Commonwealth", location: "Boston", pricePerNight: 160, rating: 4.6 },
  { id: "4", name: "Hampton Inn Boston", location: "Boston", pricePerNight: 140, rating: 4.4 },
  {
    id: "5",
    name: "Holiday Inn Express Boston",
    location: "Boston",
    pricePerNight: 130,
    rating: 4.3,
  },
  { id: "6", name: "Hyatt Regency Boston", location: "Boston", pricePerNight: 155, rating: 4.6 },
  { id: "7", name: "The Westin Copley Place", location: "Boston", pricePerNight: 170, rating: 4.7 },
  {
    id: "8",
    name: "Marriott Boston Long Wharf",
    location: "Boston",
    pricePerNight: 160,
    rating: 4.5,
  },
  { id: "9", name: "W Boston", location: "Boston", pricePerNight: 190, rating: 4.6 },
  { id: "10", name: "Eliot Hotel", location: "Boston", pricePerNight: 165, rating: 4.4 },
];

// export const hotelsData = [
//   { id: "1", name: "Hotel Le Meurice", location: "Paris", pricePerNight: 300, rating: 4.7 },
//   { id: "2", name: "The Ritz-Carlton", location: "New York", pricePerNight: 500, rating: 4.8 },
//   { id: "3", name: "Marina Bay Sands", location: "Singapore", pricePerNight: 450, rating: 4.9 },
//   { id: "4", name: "The Langham", location: "London", pricePerNight: 350, rating: 4.6 },
//   { id: "5", name: "Shangri-La Hotel", location: "Bangkok", pricePerNight: 200, rating: 4.5 },
//   { id: "6", name: "Burj Al Arab", location: "Dubai", pricePerNight: 1000, rating: 4.9 },
//   { id: "7", name: "Hotel Bel-Air", location: "Los Angeles", pricePerNight: 600, rating: 4.8 },
//   { id: "8", name: "Mandarin Oriental", location: "Tokyo", pricePerNight: 400, rating: 4.7 },
//   { id: "9", name: "Four Seasons Hotel", location: "Sydney", pricePerNight: 350, rating: 4.6 },
//   {
//     id: "10",
//     name: "Fairmont Le Château Frontenac",
//     location: "Quebec City",
//     pricePerNight: 250,
//     rating: 4.5,
//   },
//   { id: "11", name: "The Plaza", location: "New York", pricePerNight: 550, rating: 4.8 },
//   { id: "12", name: "The Peninsula", location: "Hong Kong", pricePerNight: 700, rating: 4.9 },
//   { id: "13", name: "Raffles Hotel", location: "Singapore", pricePerNight: 500, rating: 4.8 },
//   {
//     id: "14",
//     name: "The Beverly Hills Hotel",
//     location: "Los Angeles",
//     pricePerNight: 650,
//     rating: 4.8,
//   },
//   { id: "15", name: "The Savoy", location: "London", pricePerNight: 400, rating: 4.7 },
//   { id: "16", name: "Taj Mahal Palace", location: "Mumbai", pricePerNight: 300, rating: 4.6 },
//   { id: "17", name: "Waldorf Astoria", location: "Dubai", pricePerNight: 600, rating: 4.7 },
//   { id: "18", name: "Park Hyatt", location: "Sydney", pricePerNight: 450, rating: 4.7 },
//   { id: "19", name: "Hotel de Paris", location: "Monaco", pricePerNight: 750, rating: 4.8 },
//   { id: "20", name: "Palace Hotel", location: "Tokyo", pricePerNight: 350, rating: 4.6 },
//   { id: "21", name: "Conrad", location: "Chicago", pricePerNight: 300, rating: 4.5 },
//   { id: "22", name: "Rosewood", location: "London", pricePerNight: 500, rating: 4.7 },
//   { id: "23", name: "The Ritz", location: "Paris", pricePerNight: 800, rating: 4.9 },
//   { id: "24", name: "The Westin", location: "Seattle", pricePerNight: 250, rating: 4.5 },
//   { id: "25", name: "Hilton", location: "Dubai", pricePerNight: 400, rating: 4.6 },
//   {
//     id: "26",
//     name: "InterContinental",
//     location: "San Francisco",
//     pricePerNight: 300,
//     rating: 4.5,
//   },
//   { id: "27", name: "Hyatt Regency", location: "Vancouver", pricePerNight: 200, rating: 4.4 },
//   { id: "28", name: "Sheraton", location: "Buenos Aires", pricePerNight: 150, rating: 4.3 },
//   { id: "29", name: "Marriott", location: "Miami", pricePerNight: 250, rating: 4.5 },
//   { id: "30", name: "Novotel", location: "Barcelona", pricePerNight: 180, rating: 4.4 },
// ];
