export const restaurantsData = [
  { id: "1", name: "Le Jules Verne", cuisine: "French", location: "Paris", rating: 4.8 },
  { id: "2", name: "Nobu", cuisine: "Japanese", location: "New York", rating: 4.7 },
  { id: "3", name: "Osteria Francescana", cuisine: "Italian", location: "Modena", rating: 4.9 },
  { id: "4", name: "Gordon Ramsay Steak", cuisine: "British", location: "Las Vegas", rating: 4.6 },
  { id: "5", name: "Din Tai Fung", cuisine: "Chinese", location: "Shanghai", rating: 4.5 },
  { id: "6", name: "Pujol", cuisine: "Mexican", location: "Mexico City", rating: 4.9 },
  {
    id: "7",
    name: "Blue Hill at Stone Barns",
    cuisine: "American",
    location: "New York",
    rating: 4.8,
  },
  { id: "8", name: "El Celler de Can Roca", cuisine: "Spanish", location: "Girona", rating: 4.9 },
  { id: "9", name: "Restaurant Guy Savoy", cuisine: "French", location: "Paris", rating: 4.9 },
  { id: "10", name: "Sushi Saito", cuisine: "Japanese", location: "Tokyo", rating: 4.9 },
  { id: "11", name: "Alinea", cuisine: "American", location: "Chicago", rating: 4.8 },
  { id: "12", name: "Le Bernardin", cuisine: "French", location: "New York", rating: 4.8 },
  { id: "13", name: "The Ledbury", cuisine: "British", location: "London", rating: 4.7 },
  { id: "14", name: "Attica", cuisine: "Australian", location: "Melbourne", rating: 4.7 },
  { id: "15", name: "Arzak", cuisine: "Spanish", location: "San Sebastián", rating: 4.8 },
  { id: "16", name: "Per Se", cuisine: "American", location: "New York", rating: 4.8 },
  { id: "17", name: "Quintonil", cuisine: "Mexican", location: "Mexico City", rating: 4.8 },
  { id: "18", name: "Tickets", cuisine: "Spanish", location: "Barcelona", rating: 4.7 },
  { id: "19", name: "Eleven Madison Park", cuisine: "American", location: "New York", rating: 4.9 },
  { id: "20", name: "The Fat Duck", cuisine: "British", location: "Bray", rating: 4.8 },
  {
    id: "21",
    name: "The French Laundry",
    cuisine: "American",
    location: "Napa Valley",
    rating: 4.9,
  },
  { id: "22", name: "Gaggan", cuisine: "Indian", location: "Bangkok", rating: 4.9 },
  { id: "23", name: "Noma", cuisine: "Nordic", location: "Copenhagen", rating: 4.9 },
  { id: "24", name: "Central", cuisine: "Peruvian", location: "Lima", rating: 4.9 },
  { id: "25", name: "D.O.M.", cuisine: "Brazilian", location: "São Paulo", rating: 4.8 },
  { id: "26", name: "Sukiyabashi Jiro", cuisine: "Japanese", location: "Tokyo", rating: 4.8 },
  { id: "27", name: "Mirazur", cuisine: "French", location: "Menton", rating: 4.9 },
  { id: "28", name: "Geranium", cuisine: "Nordic", location: "Copenhagen", rating: 4.9 },
  { id: "29", name: "Mugaritz", cuisine: "Spanish", location: "San Sebastián", rating: 4.8 },
  { id: "30", name: "Steirereck", cuisine: "Austrian", location: "Vienna", rating: 4.8 },
];
