export const attractionsData = [
  {
    name: "Boston Common",
    description: "The oldest public park in the United States.",
    location: { city: "Boston", country: "USA" },
    category: "Scenic Spot",
    imageUrl: "https://example.com/boston_common.jpg",
    recommendedVisitTime: "2 hours",
    popularityScore: 85,
    openingHours: { open: "06:00", close: "22:00" },
    entryFee: 0,
  },
  {
    name: "Freedom Trail",
    description: "A 2.5-mile-long path through downtown Boston.",
    location: { city: "Boston", country: "USA" },
    category: "Historical Site",
    imageUrl: "https://example.com/freedom_trail.jpg",
    recommendedVisitTime: "3 hours",
    popularityScore: 90,
    openingHours: { open: "08:00", close: "20:00" },
    entryFee: 0,
  },
  {
    name: "New England Aquarium",
    description: "Aquarium with a variety of marine life exhibits.",
    location: { city: "Boston", country: "USA" },
    category: "Museum",
    imageUrl: "https://example.com/aquarium.jpg",
    recommendedVisitTime: "2 hours",
    popularityScore: 88,
    openingHours: { open: "09:00", close: "18:00" },
    entryFee: 30,
  },
  {
    name: "Museum of Fine Arts",
    description: "One of the most comprehensive art museums in the world.",
    location: { city: "Boston", country: "USA" },
    category: "Museum",
    imageUrl: "https://example.com/mfa.jpg",
    recommendedVisitTime: "3 hours",
    popularityScore: 92,
    openingHours: { open: "10:00", close: "17:00" },
    entryFee: 25,
  },
  {
    name: "Fenway Park",
    description: "Home of the Boston Red Sox and one of the oldest Major League Baseball stadiums.",
    location: { city: "Boston", country: "USA" },
    category: "Landmark",
    imageUrl: "https://example.com/fenway_park.jpg",
    recommendedVisitTime: "2 hours",
    popularityScore: 87,
    openingHours: { open: "09:00", close: "17:00" },
    entryFee: 20,
  },
  {
    name: "Boston Tea Party Ships and Museum",
    description: "Interactive museum detailing the Boston Tea Party.",
    location: { city: "Boston", country: "USA" },
    category: "Historical Site",
    imageUrl: "https://example.com/tea_party.jpg",
    recommendedVisitTime: "2 hours",
    popularityScore: 86,
    openingHours: { open: "10:00", close: "17:00" },
    entryFee: 28,
  },
  {
    name: "Isabella Stewart Gardner Museum",
    description: "Museum with a unique collection of art and beautiful gardens.",
    location: { city: "Boston", country: "USA" },
    category: "Museum",
    imageUrl: "https://example.com/gardner_museum.jpg",
    recommendedVisitTime: "2 hours",
    popularityScore: 85,
    openingHours: { open: "11:00", close: "17:00" },
    entryFee: 15,
  },
  {
    name: "Paul Revere House",
    description: "Historic house and home of Paul Revere.",
    location: { city: "Boston", country: "USA" },
    category: "Historical Site",
    imageUrl: "https://example.com/revere_house.jpg",
    recommendedVisitTime: "1 hour",
    popularityScore: 82,
    openingHours: { open: "09:30", close: "17:15" },
    entryFee: 10,
  },
  {
    name: "Boston Public Library",
    description: "Historic library with a vast collection of books and beautiful architecture.",
    location: { city: "Boston", country: "USA" },
    category: "Landmark",
    imageUrl: "https://example.com/bpl.jpg",
    recommendedVisitTime: "1.5 hours",
    popularityScore: 80,
    openingHours: { open: "09:00", close: "17:00" },
    entryFee: 0,
  },
  {
    name: "Harvard University",
    description: "Famous Ivy League university with historic buildings and museums.",
    location: { city: "Cambridge", country: "USA" },
    category: "Educational",
    imageUrl: "https://example.com/harvard.jpg",
    recommendedVisitTime: "2 hours",
    popularityScore: 84,
    openingHours: { open: "09:00", close: "17:00" },
    entryFee: 0,
  },
  {
    name: "MIT Museum",
    description: "Museum showcasing technology and innovation from MIT.",
    location: { city: "Cambridge", country: "USA" },
    category: "Museum",
    imageUrl: "https://example.com/mit_museum.jpg",
    recommendedVisitTime: "1.5 hours",
    popularityScore: 83,
    openingHours: { open: "10:00", close: "17:00" },
    entryFee: 10,
  },
];

// export const attractionsData = [
//   {
//     name: "Eiffel Tower",
//     description: "Iconic symbol of France, offering panoramic views of Paris.",
//     location: { city: "Paris", country: "France" },
//     category: "Landmark",
//     imageUrl: "https://example.com/eiffel.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 95,
//     openingHours: { open: "09:00", close: "00:00" },
//     entryFee: 25,
//   },
//   {
//     name: "Louvre Museum",
//     description: "World's largest art museum and a historic monument in Paris.",
//     location: { city: "Paris", country: "France" },
//     category: "Museum",
//     imageUrl: "https://example.com/louvre.jpg",
//     recommendedVisitTime: "4 hours",
//     popularityScore: 90,
//     openingHours: { open: "09:00", close: "18:00" },
//     entryFee: 17,
//   },
//   {
//     name: "Statue of Liberty",
//     description: "A colossal neoclassical sculpture on Liberty Island.",
//     location: { city: "New York", country: "USA" },
//     category: "Landmark",
//     imageUrl: "https://example.com/liberty.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 88,
//     openingHours: { open: "08:30", close: "16:00" },
//     entryFee: 18,
//   },
//   {
//     name: "Great Wall of China",
//     description: "Ancient series of walls and fortifications, totaling more than 13,000 miles.",
//     location: { city: "Beijing", country: "China" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/greatwall.jpg",
//     recommendedVisitTime: "5 hours",
//     popularityScore: 92,
//     openingHours: { open: "07:30", close: "17:30" },
//     entryFee: 40,
//   },
//   {
//     name: "Machu Picchu",
//     description: "15th-century Inca citadel set high in the Andes Mountains.",
//     location: { city: "Cusco", country: "Peru" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/machu.jpg",
//     recommendedVisitTime: "4 hours",
//     popularityScore: 94,
//     openingHours: { open: "06:00", close: "18:00" },
//     entryFee: 60,
//   },
//   {
//     name: "Colosseum",
//     description: "An ancient amphitheater in the center of Rome.",
//     location: { city: "Rome", country: "Italy" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/colosseum.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 90,
//     openingHours: { open: "08:30", close: "19:00" },
//     entryFee: 15,
//   },
//   {
//     name: "Sydney Opera House",
//     description: "Multi-venue performing arts centre in Sydney.",
//     location: { city: "Sydney", country: "Australia" },
//     category: "Landmark",
//     imageUrl: "https://example.com/opera.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 85,
//     openingHours: { open: "09:00", close: "17:00" },
//     entryFee: 30,
//   },
//   {
//     name: "Christ the Redeemer",
//     description: "A giant statue of Jesus Christ in Rio de Janeiro.",
//     location: { city: "Rio de Janeiro", country: "Brazil" },
//     category: "Landmark",
//     imageUrl: "https://example.com/christ.jpg",
//     recommendedVisitTime: "1 hour",
//     popularityScore: 89,
//     openingHours: { open: "08:00", close: "19:00" },
//     entryFee: 20,
//   },
//   {
//     name: "Taj Mahal",
//     description: "Ivory-white marble mausoleum in Agra, India.",
//     location: { city: "Agra", country: "India" },
//     category: "Landmark",
//     imageUrl: "https://example.com/tajmahal.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 96,
//     openingHours: { open: "06:00", close: "19:00" },
//     entryFee: 25,
//   },
//   {
//     name: "Santorini",
//     description: "Greek island known for its stunning views, sunsets, and beaches.",
//     location: { city: "Santorini", country: "Greece" },
//     category: "Scenic Spot",
//     imageUrl: "https://example.com/santorini.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 87,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 0,
//   },
//   {
//     name: "Golden Gate Bridge",
//     description: "Famous suspension bridge in San Francisco.",
//     location: { city: "San Francisco", country: "USA" },
//     category: "Landmark",
//     imageUrl: "https://example.com/golden.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 85,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 0,
//   },
//   {
//     name: "Mount Fuji",
//     description: "Japan's tallest mountain and an active volcano.",
//     location: { city: "Honshu", country: "Japan" },
//     category: "Scenic Spot",
//     imageUrl: "https://example.com/fuji.jpg",
//     recommendedVisitTime: "5 hours",
//     popularityScore: 90,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 0,
//   },
//   {
//     name: "Burj Khalifa",
//     description: "Tallest building in the world, located in Dubai.",
//     location: { city: "Dubai", country: "UAE" },
//     category: "Landmark",
//     imageUrl: "https://example.com/burj.jpg",
//     recommendedVisitTime: "1 hour",
//     popularityScore: 88,
//     openingHours: { open: "08:00", close: "22:00" },
//     entryFee: 40,
//   },
//   {
//     name: "Niagara Falls",
//     description: "Famous waterfalls on the border of Ontario and New York.",
//     location: { city: "Niagara Falls", country: "Canada" },
//     category: "Scenic Spot",
//     imageUrl: "https://example.com/niagara.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 85,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 0,
//   },
//   {
//     name: "Chichen Itza",
//     description: "Large pre-Columbian archaeological site in Mexico.",
//     location: { city: "Yucatán", country: "Mexico" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/chichen.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 90,
//     openingHours: { open: "08:00", close: "17:00" },
//     entryFee: 20,
//   },
//   {
//     name: "Petra",
//     description: "Historical and archaeological city in southern Jordan.",
//     location: { city: "Ma'an", country: "Jordan" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/petra.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 91,
//     openingHours: { open: "06:00", close: "18:00" },
//     entryFee: 30,
//   },
//   {
//     name: "Acropolis of Athens",
//     description: "Ancient citadel located on a rocky outcrop above the city of Athens.",
//     location: { city: "Athens", country: "Greece" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/acropolis.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 88,
//     openingHours: { open: "08:00", close: "19:00" },
//     entryFee: 20,
//   },
//   {
//     name: "Sagrada Familia",
//     description: "Large unfinished Roman Catholic minor basilica in Barcelona.",
//     location: { city: "Barcelona", country: "Spain" },
//     category: "Landmark",
//     imageUrl: "https://example.com/sagrada.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 89,
//     openingHours: { open: "09:00", close: "18:00" },
//     entryFee: 20,
//   },
//   {
//     name: "Great Barrier Reef",
//     description: "World's largest coral reef system.",
//     location: { city: "Cairns", country: "Australia" },
//     category: "Scenic Spot",
//     imageUrl: "https://example.com/reef.jpg",
//     recommendedVisitTime: "4 hours",
//     popularityScore: 94,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 0,
//   },
//   {
//     name: "Alhambra",
//     description: "Palace and fortress complex located in Granada, Spain.",
//     location: { city: "Granada", country: "Spain" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/alhambra.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 86,
//     openingHours: { open: "08:30", close: "20:00" },
//     entryFee: 14,
//   },
//   {
//     name: "Mount Everest",
//     description: "Earth's highest mountain above sea level.",
//     location: { city: "Solukhumbu", country: "Nepal" },
//     category: "Scenic Spot",
//     imageUrl: "https://example.com/everest.jpg",
//     recommendedVisitTime: "5 hours",
//     popularityScore: 95,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 0,
//   },
//   {
//     name: "Times Square",
//     description: "Major commercial intersection and tourist destination in New York City.",
//     location: { city: "New York", country: "USA" },
//     category: "Landmark",
//     imageUrl: "https://example.com/times.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 87,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 0,
//   },
//   {
//     name: "Vatican Museums",
//     description: "Christian art museums located in Vatican City.",
//     location: { city: "Vatican City", country: "Vatican" },
//     category: "Museum",
//     imageUrl: "https://example.com/vatican.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 92,
//     openingHours: { open: "09:00", close: "18:00" },
//     entryFee: 17,
//   },
//   {
//     name: "Angkor Wat",
//     description: "Largest religious monument in the world, located in Cambodia.",
//     location: { city: "Siem Reap", country: "Cambodia" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/angkor.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 90,
//     openingHours: { open: "05:00", close: "18:00" },
//     entryFee: 37,
//   },
//   {
//     name: "Grand Canyon",
//     description:
//       "Famous canyon in Arizona, USA, known for its immense size and colorful landscape.",
//     location: { city: "Arizona", country: "USA" },
//     category: "Scenic Spot",
//     imageUrl: "https://example.com/grandcanyon.jpg",
//     recommendedVisitTime: "4 hours",
//     popularityScore: 93,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 35,
//   },
//   {
//     name: "Neuschwanstein Castle",
//     description: "19th-century Romanesque Revival palace in Germany.",
//     location: { city: "Schwangau", country: "Germany" },
//     category: "Landmark",
//     imageUrl: "https://example.com/neuschwanstein.jpg",
//     recommendedVisitTime: "2 hours",
//     popularityScore: 88,
//     openingHours: { open: "09:00", close: "18:00" },
//     entryFee: 15,
//   },
//   {
//     name: "Palace of Versailles",
//     description: "Former royal residence located in Versailles, France.",
//     location: { city: "Versailles", country: "France" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/versailles.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 89,
//     openingHours: { open: "09:00", close: "18:30" },
//     entryFee: 18,
//   },
//   {
//     name: "Matterhorn",
//     description: "Mountain in the Pennine Alps on the border between Switzerland and Italy.",
//     location: { city: "Zermatt", country: "Switzerland" },
//     category: "Scenic Spot",
//     imageUrl: "https://example.com/matterhorn.jpg",
//     recommendedVisitTime: "4 hours",
//     popularityScore: 92,
//     openingHours: { open: "00:00", close: "23:59" },
//     entryFee: 0,
//   },
//   {
//     name: "Stonehenge",
//     description: "Prehistoric monument in Wiltshire, England.",
//     location: { city: "Wiltshire", country: "England" },
//     category: "Historical Site",
//     imageUrl: "https://example.com/stonehenge.jpg",
//     recommendedVisitTime: "1 hour",
//     popularityScore: 84,
//     openingHours: { open: "09:00", close: "17:00" },
//     entryFee: 20,
//   },
//   {
//     name: "Table Mountain",
//     description:
//       "Flat-topped mountain forming a prominent landmark overlooking the city of Cape Town.",
//     location: { city: "Cape Town", country: "South Africa" },
//     category: "Scenic Spot",
//     imageUrl: "https://example.com/tablemountain.jpg",
//     recommendedVisitTime: "3 hours",
//     popularityScore: 90,
//     openingHours: { open: "07:00", close: "19:00" },
//     entryFee: 15,
//   },
// ];
